version: '3.4'

services:
  cachingwithredis:
    container_name: cachingwithredis.api
    image: ${DOCKER_REGISTRY-}cachingwithredis
    ports:
      - 8080:8080
      - 8081:8081 
    build:
      context: .
      dockerfile: CachingWithRedis/Dockerfile
    depends_on:
      cachingwithredis.database:
        condition: service_healthy
  cachingwithredis.database:
    container_name: cachingwithredis.database
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: CachingWithRedis
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: password123
    volumes:
      - ./containers/cachingwithredis-db:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
